# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23e05f7e828042659973ff074a148748325413c447025016a60aeed8bf73926aac3ff7a29e21a3bfb2afbeb81deeab972127d653e6df88378874c10c26a26b3c

test:
  secret_key_base: 2bbd735c9e0b0488561342db653b6dc6c9b888274bd81249b82c5d866264693835a939dd93b2b9f1ece92871e91de753dab7893773e172de81633c5aac53ca0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
